// ============================================================================
// DOMAIN MODULE: ADMIN, SECURITY & SYSTEM GOVERNANCE
// Modular Monolithic Architecture — Reboot ERP
// ============================================================================

export { AdminViews } from '../../components/AdminViews';
export {
  systemHealth,
  adminUsers,
  adminRoles,
  companyProfile,
  numberingSequences,
  approvalWorkflows,
  securityPolicy,
  auditLogs,
  integrations,
  backupRecords,
  notificationTemplates,
  systemParameters,
  mockSystemHealth,
  mockAdminUsers,
  mockAdminRoles,
  mockCompanyProfile,
  mockNumberingSequences,
  mockApprovalWorkflows,
  mockSecurityPolicy,
  mockAuditLogs,
  mockIntegrations,
  mockBackupRecords,
  mockNotificationTemplates,
  mockSystemParameters,
} from '../../data/adminData';
export {
  userGroups,
  workflowConfigs,
  warehouseLocations,
  machineWorkCenters,
  shifts,
  holidays,
  reasonCodes,
  masterDataRecords,
  documentPolicies,
  loginAuditRecords,
  dataExchangeJobs,
  retentionPolicies,
  licenseDetails,
  sodRules,
  sodViolations,
  simulationScenarios,
  multiContextPolicies,
  rowLevelSecurityRules,
  breakGlassRequests,
  mockUserGroups,
  mockWorkflowConfigs,
  mockWarehouseLocations,
  mockMachineWorkCenters,
  mockShifts,
  mockHolidays,
  mockReasonCodes,
  mockMasterDataRecords,
  mockDocumentPolicies,
  mockLoginAuditRecords,
  mockDataExchangeJobs,
  mockRetentionPolicies,
  mockLicenseDetails,
  mockSodRules,
  mockSodViolations,
  mockSimulationScenarios,
  mockMultiContextPolicies,
  mockRowLevelSecurityRules,
  mockBreakGlassRequests,
} from '../../data/adminExtendedData';

export type {
  AdminSystemHealth,
  AdminUser,
  AdminRole,
  CompanyProfile,
  NumberingSequence,
  ApprovalWorkflow,
  SecurityPolicySettings,
  AuditLogEntry,
  IntegrationConnector,
  BackupRecord,
  NotificationTemplate,
  SystemParameter,
  RoleSimulationScenario,
  SodConflictRule,
  SodViolation,
  MultiContextScopePolicy,
  RowLevelSecurityRule,
  BreakGlassRequest,
} from '../../types/admin';
