import React, { useState, useMemo } from 'react';
import {
  Search,
  Plus,
  Filter,
  FileText,
  Clock,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Sparkles,
  Download,
  Calendar,
  Layers,
  ChevronRight,
} from 'lucide-react';
import { PurchaseRequisition } from '../../types/procurement';
import { ProcurementStatusBadge } from './ProcurementStatusBadge';
import { PaginationBar } from '../common/PaginationBar';

interface Props {
  prs: PurchaseRequisition[];
  onNavigate: (view: string, param?: any) => void;
  onUpdatePR: (pr: PurchaseRequisition) => void;
  showToast: (msg: string) => void;
}

export const PurchaseRequisitionListView: React.FC<Props> = ({
  prs,
  onNavigate,
  onUpdatePR,
  showToast,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState<string>('All');
  const [selectedPriority, setSelectedPriority] = useState<string>('All');
  const [selectedSource, setSelectedSource] = useState<string>('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const filteredPrs = useMemo(() => {
    return prs.filter((pr) => {
      const matchSearch =
        pr.prNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
        pr.requestedBy.toLowerCase().includes(searchTerm.toLowerCase()) ||
        pr.department.toLowerCase().includes(searchTerm.toLowerCase()) ||
        pr.lines.some((l) => l.itemName.toLowerCase().includes(searchTerm.toLowerCase()) || l.itemCode.toLowerCase().includes(searchTerm.toLowerCase()));

      const matchStatus = selectedStatus === 'All' || pr.status === selectedStatus;
      const matchPriority = selectedPriority === 'All' || pr.priority === selectedPriority;
      const matchSource = selectedSource === 'All' || pr.source === selectedSource;

      return matchSearch && matchStatus && matchPriority && matchSource;
    });
  }, [prs, searchTerm, selectedStatus, selectedPriority, selectedSource]);

  const totalPages = Math.ceil(filteredPrs.length / pageSize) || 1;
  const paginatedPrs = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return filteredPrs.slice(start, start + pageSize);
  }, [filteredPrs, currentPage, pageSize]);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold font-['Space_Grotesk'] text-[#14213D]">
            Purchase Requisitions (PR)
          </h1>
          <p className="text-xs text-slate-500">
            Internal material requests generated by MRP shortage engine, work orders, and plant maintenance
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={() => onNavigate('mrpSuggestions')}
            className="flex items-center gap-1.5 px-3 py-2 bg-[#E8622C] hover:bg-[#d45320] text-white rounded-lg text-xs font-semibold shadow-sm transition"
          >
            <Sparkles className="w-3.5 h-3.5" /> MRP Suggestions
          </button>
          <button
            onClick={() => onNavigate('prCreate')}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-[#0F8B8D] hover:bg-[#0d797b] text-white rounded-lg text-xs font-semibold shadow-sm transition"
          >
            <Plus className="w-3.5 h-3.5" /> Create PR
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder="Search by PR #, requester, material name, or SKU..."
            value={searchTerm}
            onChange={(e) => {
              setSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
            className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-xs focus:outline-none focus:ring-1 focus:ring-[#0F8B8D]"
          />
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <select
            value={selectedStatus}
            onChange={(e) => {
              setSelectedStatus(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Statuses</option>
            <option value="pending_approval">Pending Approval</option>
            <option value="approved">Approved</option>
            <option value="converted_po">Converted to PO</option>
            <option value="converted_rfq">Converted to RFQ</option>
            <option value="draft">Draft</option>
            <option value="rejected">Rejected</option>
          </select>

          <select
            value={selectedPriority}
            onChange={(e) => {
              setSelectedPriority(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Priorities</option>
            <option value="Urgent">Urgent</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>

          <select
            value={selectedSource}
            onChange={(e) => {
              setSelectedSource(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Sources</option>
            <option value="MRP">MRP Engine</option>
            <option value="Production Work Order">Production WO</option>
            <option value="Maintenance Job">Maintenance Job</option>
            <option value="Manual">Manual</option>
          </select>
        </div>
      </div>

      {/* PR Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-50 text-slate-600 uppercase text-[10px] tracking-wider border-b border-slate-200">
              <tr>
                <th className="py-3 px-3 font-semibold">PR Number</th>
                <th className="py-3 px-3 font-semibold">Requester & Dept</th>
                <th className="py-3 px-3 font-semibold">Source</th>
                <th className="py-3 px-3 font-semibold">Requested Materials</th>
                <th className="py-3 px-3 font-semibold">Required Date</th>
                <th className="py-3 px-3 font-semibold text-right">Est. Value</th>
                <th className="py-3 px-3 font-semibold text-center">Priority</th>
                <th className="py-3 px-3 font-semibold text-center">Status</th>
                <th className="py-3 px-3 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {paginatedPrs.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-8 text-center text-slate-400">
                    No purchase requisitions found.
                  </td>
                </tr>
              ) : (
                paginatedPrs.map((pr) => (
                  <tr
                    key={pr.id}
                    className="hover:bg-slate-50/80 transition cursor-pointer group"
                    onClick={() => onNavigate('prDetail', { id: pr.id })}
                  >
                    {/* PR Number */}
                    <td className="py-3 px-3">
                      <div className="font-bold text-[#14213D] group-hover:text-[#0F8B8D] font-mono">
                        {pr.prNumber}
                      </div>
                      <div className="text-[10px] text-slate-500">{pr.requestDate}</div>
                    </td>

                    {/* Requester */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">{pr.requestedBy}</div>
                      <div className="text-[10px] text-slate-500">{pr.department}</div>
                    </td>

                    {/* Source */}
                    <td className="py-3 px-3">
                      <span className="px-2 py-0.5 rounded bg-slate-100 text-slate-700 text-[10px] font-semibold">
                        {pr.source}
                      </span>
                    </td>

                    {/* Lines Summary */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">
                        {pr.lines[0]?.itemName || 'Materials'}
                      </div>
                      <div className="text-[10px] text-slate-500">
                        {pr.lines[0]?.quantity.toLocaleString()} {pr.lines[0]?.uom} {pr.lines.length > 1 && `+ ${pr.lines.length - 1} more lines`}
                      </div>
                    </td>

                    {/* Required Date */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">{pr.requiredDate}</div>
                      <div className="text-[10px] text-slate-500">{pr.plantWarehouse}</div>
                    </td>

                    {/* Est. Total */}
                    <td className="py-3 px-3 text-right font-bold text-[#14213D]">
                      ₹{(pr.estimatedTotal / 100000).toFixed(2)} Lakhs
                    </td>

                    {/* Priority */}
                    <td className="py-3 px-3 text-center">
                      <span
                        className={`inline-block px-2 py-0.5 rounded text-[10px] font-bold ${
                          pr.priority === 'Urgent'
                            ? 'bg-red-100 text-red-800'
                            : pr.priority === 'High'
                            ? 'bg-amber-100 text-amber-800'
                            : 'bg-slate-100 text-slate-700'
                        }`}
                      >
                        {pr.priority}
                      </span>
                    </td>

                    {/* Status */}
                    <td className="py-3 px-3 text-center">
                      <ProcurementStatusBadge status={pr.status} size="xs" />
                    </td>

                    {/* Actions */}
                    <td className="py-3 px-3 text-right" onClick={(e) => e.stopPropagation()}>
                      <div className="flex items-center justify-end gap-1.5">
                        {pr.status === 'approved' && (
                          <button
                            onClick={() => {
                              showToast(`Converted ${pr.prNumber} into Purchase Order`);
                              onNavigate('poList');
                            }}
                            className="px-2 py-1 bg-[#0F8B8D] text-white rounded text-[11px] font-semibold hover:bg-[#0d797b]"
                          >
                            + Create PO
                          </button>
                        )}
                        {pr.status === 'pending_approval' && (
                          <button
                            onClick={() => onNavigate('prDetail', { id: pr.id })}
                            className="px-2 py-1 bg-amber-600 text-white rounded text-[11px] font-semibold hover:bg-amber-700"
                          >
                            Review & Approve
                          </button>
                        )}
                        <button
                          onClick={() => onNavigate('prDetail', { id: pr.id })}
                          className="p-1 hover:bg-slate-100 rounded text-slate-500"
                        >
                          <ChevronRight className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <PaginationBar
          currentPage={currentPage}
          totalPages={totalPages}
          pageSize={pageSize}
          totalItems={filteredPrs.length}
          onPageChange={setCurrentPage}
          onPageSizeChange={(sz) => {
            setPageSize(sz);
            setCurrentPage(1);
          }}
          itemName="requisitions"
        />
      </div>
    </div>
  );
};
