import React, { useState, useMemo } from 'react';
import {
  Search,
  Plus,
  Filter,
  FileText,
  Clock,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Sparkles,
  Download,
  Calendar,
  Layers,
  ChevronRight,
  Factory,
  Package,
  ShieldCheck,
  X,
  Send,
  Building2,
} from 'lucide-react';
import { PurchaseRequisition } from '../../types/procurement';
import { ProcurementStatusBadge } from './ProcurementStatusBadge';
import { PaginationBar } from '../common/PaginationBar';
import { computePlantBomExplosion } from '../../services/procurement/bomExplosionService';
import { PrBomVendorWorkbenchModal } from './PrBomVendorWorkbenchModal';

interface Props {
  prs: PurchaseRequisition[];
  onNavigate: (view: string, param?: any) => void;
  onUpdatePR: (pr: PurchaseRequisition) => void;
  showToast: (msg: string) => void;
}

export const PurchaseRequisitionListView: React.FC<Props> = ({
  prs,
  onNavigate,
  onUpdatePR,
  showToast,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState<string>('All');
  const [selectedPriority, setSelectedPriority] = useState<string>('All');
  const [selectedSource, setSelectedSource] = useState<string>('All');
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  // Task-3: BOM Explosion & Supplier Intelligence Modal state in Procurement
  const [selectedPrForBom, setSelectedPrForBom] = useState<PurchaseRequisition | null>(null);
  const [isBomModalOpen, setIsBomModalOpen] = useState<boolean>(false);
  const [activeBomTab, setActiveBomTab] = useState<'bom' | 'suppliers' | 'preview'>('bom');

  const filteredPrs = useMemo(() => {
    return (prs || []).filter((pr) => {
      if (!pr) return false;
      const prNum = pr.prNumber || '';
      const reqBy = pr.requestedBy || '';
      const dept = pr.department || '';
      const linesList = pr.lines || [];
      const q = searchTerm.toLowerCase().trim();

      const matchSearch =
        !q ||
        prNum.toLowerCase().includes(q) ||
        reqBy.toLowerCase().includes(q) ||
        dept.toLowerCase().includes(q) ||
        linesList.some(
          (l) =>
            (l?.itemName || '').toLowerCase().includes(q) ||
            (l?.itemCode || '').toLowerCase().includes(q)
        );

      const matchStatus = selectedStatus === 'All' || pr.status === selectedStatus;
      const matchPriority = selectedPriority === 'All' || pr.priority === selectedPriority;
      const matchSource = selectedSource === 'All' || pr.source === selectedSource;

      return matchSearch && matchStatus && matchPriority && matchSource;
    });
  }, [prs, searchTerm, selectedStatus, selectedPriority, selectedSource]);

  const totalPages = Math.ceil(filteredPrs.length / pageSize) || 1;
  const paginatedPrs = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return filteredPrs.slice(start, start + pageSize);
  }, [filteredPrs, currentPage, pageSize]);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold font-['Space_Grotesk'] text-[#14213D]">
            Purchase Requisitions (PR)
          </h1>
          <p className="text-xs text-slate-500">
            Internal material requests generated by MRP shortage engine, work orders, and plant maintenance
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={() => onNavigate('mrpSuggestions')}
            className="flex items-center gap-1.5 px-3 py-2 bg-[#E8622C] hover:bg-[#d45320] text-white rounded-lg text-xs font-semibold shadow-sm transition"
          >
            <Sparkles className="w-3.5 h-3.5" /> MRP Suggestions
          </button>
          <button
            onClick={() => onNavigate('prCreate')}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-[#0F8B8D] hover:bg-[#0d797b] text-white rounded-lg text-xs font-semibold shadow-sm transition"
          >
            <Plus className="w-3.5 h-3.5" /> Create PR
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder="Search by PR #, requester, material name, or SKU..."
            value={searchTerm}
            onChange={(e) => {
              setSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
            className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-xs focus:outline-none focus:ring-1 focus:ring-[#0F8B8D]"
          />
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <select
            value={selectedStatus}
            onChange={(e) => {
              setSelectedStatus(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Statuses</option>
            <option value="pending_approval">Pending Approval</option>
            <option value="approved">Approved</option>
            <option value="converted_po">Converted to PO</option>
            <option value="converted_rfq">Converted to RFQ</option>
            <option value="draft">Draft</option>
            <option value="rejected">Rejected</option>
          </select>

          <select
            value={selectedPriority}
            onChange={(e) => {
              setSelectedPriority(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Priorities</option>
            <option value="Urgent">Urgent</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>

          <select
            value={selectedSource}
            onChange={(e) => {
              setSelectedSource(e.target.value);
              setCurrentPage(1);
            }}
            className="px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white text-slate-700"
          >
            <option value="All">All Sources</option>
            <option value="MRP">MRP Engine</option>
            <option value="Production Work Order">Production WO</option>
            <option value="Maintenance Job">Maintenance Job</option>
            <option value="Manual">Manual</option>
          </select>
        </div>
      </div>

      {/* PR Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-50 text-slate-600 uppercase text-[10px] tracking-wider border-b border-slate-200">
              <tr>
                <th className="py-3 px-3 font-semibold">PR Number</th>
                <th className="py-3 px-3 font-semibold">Requester & Dept</th>
                <th className="py-3 px-3 font-semibold">Source</th>
                <th className="py-3 px-3 font-semibold">Requested Materials</th>
                <th className="py-3 px-3 font-semibold">Required Date</th>
                <th className="py-3 px-3 font-semibold text-right">Est. Value</th>
                <th className="py-3 px-3 font-semibold text-center">Priority</th>
                <th className="py-3 px-3 font-semibold text-center">Status</th>
                <th className="py-3 px-3 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {paginatedPrs.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-8 text-center text-slate-400">
                    No purchase requisitions found.
                  </td>
                </tr>
              ) : (
                paginatedPrs.map((pr) => (
                  <tr
                    key={pr.id}
                    className="hover:bg-slate-50/80 transition cursor-pointer group"
                    onClick={() => onNavigate('prDetail', { id: pr.id })}
                  >
                    {/* PR Number */}
                    <td className="py-3 px-3">
                      <div className="font-bold text-[#14213D] group-hover:text-[#0F8B8D] font-mono">
                        {pr.prNumber}
                      </div>
                      <div className="text-[10px] text-slate-500">{pr.requestDate}</div>
                    </td>

                    {/* Requester */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">{pr.requestedBy}</div>
                      <div className="text-[10px] text-slate-500">{pr.department}</div>
                    </td>

                    {/* Source */}
                    <td className="py-3 px-3">
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <span className="px-2 py-0.5 rounded bg-slate-100 text-slate-700 text-[10px] font-semibold">
                          {pr.source}
                        </span>
                        {(pr.source === 'Monthly Plan Order' || (pr.lines && pr.lines.length > 0)) && (
                          <span className="px-1.5 py-0.2 rounded bg-teal-50 text-teal-700 border border-teal-200 text-[9px] font-bold">
                            BOM Linked
                          </span>
                        )}
                      </div>
                    </td>

                    {/* Lines Summary */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">
                        {(pr.lines && pr.lines[0]?.itemName) || (pr.lines && pr.lines.length > 0 ? 'Material Listed' : 'No items')}
                      </div>
                      <div className="text-[10px] text-slate-500">
                        {pr.lines && pr.lines[0]
                          ? `${Number(pr.lines[0].quantity || 0).toLocaleString('en-IN')} ${pr.lines[0].uom || 'KG'}`
                          : '0 items'}
                        {pr.lines && pr.lines.length > 1 && ` + ${pr.lines.length - 1} more lines`}
                      </div>
                    </td>

                    {/* Required Date */}
                    <td className="py-3 px-3">
                      <div className="font-medium text-[#14213D]">{pr.requiredDate}</div>
                      <div className="text-[10px] text-slate-500">{pr.plantWarehouse}</div>
                    </td>

                    {/* Est. Total */}
                    <td className="py-3 px-3 text-right font-bold text-[#14213D]">
                      ₹{((Number(pr.estimatedTotal) || 0) / 100000).toFixed(2)} Lakhs
                    </td>

                    {/* Priority */}
                    <td className="py-3 px-3 text-center">
                      <span
                        className={`inline-block px-2 py-0.5 rounded text-[10px] font-bold ${
                          pr.priority === 'Urgent'
                            ? 'bg-red-100 text-red-800'
                            : pr.priority === 'High'
                            ? 'bg-amber-100 text-amber-800'
                            : 'bg-slate-100 text-slate-700'
                        }`}
                      >
                        {pr.priority || 'Medium'}
                      </span>
                    </td>

                    {/* Status */}
                    <td className="py-3 px-3 text-center">
                      <ProcurementStatusBadge status={pr.status} size="xs" />
                    </td>

                    {/* Actions */}
                    <td className="py-3 px-3 text-right" onClick={(e) => e.stopPropagation()}>
                      <div className="flex items-center justify-end gap-1.5">
                        {/* Task-2: BOM Explosion & Supplier Suggestion Action */}
                        <button
                          onClick={() => {
                            setSelectedPrForBom(pr);
                            setIsBomModalOpen(true);
                          }}
                          className="px-2 py-1 bg-amber-500 hover:bg-amber-600 text-white rounded text-[11px] font-bold flex items-center gap-1 transition shadow-2xs cursor-pointer"
                          title="View Linked BOM Material Explosion & Approved Supplier Suggestions"
                        >
                          <Sparkles className="w-3 h-3" />
                          <span>BOM &amp; Vendors</span>
                        </button>

                        <button
                          onClick={() => {
                            showToast(`Opening PO creation wizard with lines from ${pr.prNumber}`);
                            onNavigate('poList', { openCreateModal: true, sourcePr: pr.prNumber, pr: pr });
                          }}
                          className="px-2.5 py-1 bg-[#0F8B8D] text-white rounded-lg text-[11px] font-semibold hover:bg-[#0d797b] transition shadow-2xs cursor-pointer"
                        >
                          + Issue PO
                        </button>
                        {pr.status === 'pending_approval' && (
                          <button
                            onClick={() => onNavigate('prDetail', { id: pr.id })}
                            className="px-2 py-1 bg-blue-600 text-white rounded text-[11px] font-semibold hover:bg-blue-700"
                          >
                            Review & Approve
                          </button>
                        )}
                        <button
                          onClick={() => onNavigate('prDetail', { id: pr.id })}
                          className="p-1 hover:bg-slate-100 rounded text-slate-500"
                        >
                          <ChevronRight className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <PaginationBar
          currentPage={currentPage}
          totalPages={totalPages}
          pageSize={pageSize}
          totalItems={filteredPrs.length}
          onPageChange={setCurrentPage}
          onPageSizeChange={(sz) => {
            setPageSize(sz);
            setCurrentPage(1);
          }}
          itemName="requisitions"
        />
      </div>

      {/* Dedicated PR BOM Recipe & Consolidated Vendor Intelligence Workbench Modal */}
      {isBomModalOpen && selectedPrForBom && (
        <PrBomVendorWorkbenchModal
          pr={selectedPrForBom}
          onClose={() => {
            setIsBomModalOpen(false);
            setSelectedPrForBom(null);
          }}
          onNavigate={onNavigate}
          showToast={showToast}
        />
      )}
    </div>
  );
};
